Insert INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('Aprobada');

INSERT INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('Rechazada');

INSERT INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('En revision');

INSERT INTO "ROL" ("DESCRIPCION") VALUES ('Team');

INSERT INTO "ROL" ("DESCRIPCION") VALUES ('Cliente');
