INSERT INTO "ESTADO HISTORIA DE USUARIO" ("ID_ESTADO", "DESCRIPCION") VALUES (0, 'Aprobada');
INSERT INTO "ESTADO HISTORIA DE USUARIO" ("ID_ESTADO", "DESCRIPCION") VALUES (1, 'Rechazada');
INSERT INTO "ESTADO HISTORIA DE USUARIO" ("ID_ESTADO", "DESCRIPCION") VALUES (2, 'En revision');

INSERT INTO "ROL"("ID_ROL", "DESCRIPCION") VALUES (0, 'Team');
INSERT INTO "ROL"("ID_ROL", "DESCRIPCION") VALUES (1, 'Cliente');
INSERT INTO "ROL"("ID_ROL", "DESCRIPCION") VALUES (2, 'Admin');

INSERT INTO "USER"("ID_USS", "LOGIN", "PASSWORD") VALUES (1, 'cliente', 'cliente');
INSERT INTO "USER"("ID_USS", "LOGIN", "PASSWORD") VALUES (2, 'admin', 'admin');

INSERT INTO public."PERSONA"("ID_PERSONA", "USER_ID_USS", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "CORREO", "NUMERO") VALUES (1, 1, 'Juan', 'Perez', 'Perez', 'juan@juan.com', '+591 66666666');

INSERT INTO public."PERSONA"("ID_PERSONA", "USER_ID_USS", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "CORREO", "NUMERO") VALUES (2, 2, 'Admin', 'Admin', 'Admin', 'admin@admin.com', '+591 77777777');

INSERT INTO "USS ROL"("USER_ID_USS", "ROL_ID_ROL") VALUES (1, 1);
INSERT INTO "USS ROL"("USER_ID_USS", "ROL_ID_ROL") VALUES (2, 2);

INSERT INTO "PROYECTO"("ID_PROYECTO", "DESCRIPCION", "TITULO") VALUES (1, 'XP es la luz', 'XP es la luz');

INSERT INTO "HISTORIA DE USUARIO"("ID_HU", "ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA") VALUES (1, 0, 'Aprobada', 'Mi primera historia', 10);

INSERT INTO "HISTORIA DE USUARIO"("ID_HU", "ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA", "RAZON RECHAZO") VALUES (2, 1, 'Rechazada', 'Mi Segunda historia', 5, 'No me gustaba la historia');

INSERT INTO "HISTORIA DE USUARIO"("ID_HU", "ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA" ) VALUES (3, 2, 'En revision', 'Mi tercera historia', 7);