INSERT INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('Aprobada');
INSERT INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('Rechazada');
INSERT INTO "ESTADO HISTORIA DE USUARIO" ("DESCRIPCION") VALUES ('En revision');

INSERT INTO "ROL"("DESCRIPCION") VALUES ('Team');
INSERT INTO "ROL"("DESCRIPCION") VALUES ('Cliente');
INSERT INTO "ROL"("DESCRIPCION") VALUES ('Admin');

INSERT INTO "USER"("LOGIN", "PASSWORD") VALUES ('cliente', 'cliente');
INSERT INTO "USER"("LOGIN", "PASSWORD") VALUES ('admin', 'admin');

INSERT INTO public."PERSONA"("USER_ID_USS", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "CORREO", "NUMERO") VALUES (1, 'Juan', 'Perez', 'Perez', 'juan@juan.com', '+591 66666666');

INSERT INTO public."PERSONA"("USER_ID_USS", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "CORREO", "NUMERO") VALUES (2, 'Admin', 'Admin', 'Admin', 'admin@admin.com', '+591 77777777');

INSERT INTO "USS ROL"("USER_ID_USS", "ROL_ID_ROL") VALUES (1, 2);
INSERT INTO "USS ROL"("USER_ID_USS", "ROL_ID_ROL") VALUES (2, 3);

INSERT INTO "PROYECTO"("DESCRIPCION", "TITULO") VALUES ('XP es la luz', 'XP es la luz');

INSERT INTO "HISTORIA DE USUARIO"("ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA") VALUES (1, 'Aprobada', 'Mi primera historia', 10);

INSERT INTO "HISTORIA DE USUARIO"("ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA", "RAZON RECHAZO") VALUES (2, 'Rechazada', 'Mi Segunda historia', 5, 'No me gustaba la historia');

INSERT INTO "HISTORIA DE USUARIO"("ESTADO HISTORIA DE USUARIO_ID_ESTADO", "DESCRIPCION", "NOMBRE", "IMPORTANCIA" ) VALUES (3, 'En revision', 'Mi tercera historia', 7);