package XP.Visual;
import XP.Modelo.HistoriaUsuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JProgressBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class HistoriaUsuarioInterfaz extends javax.swing.JFrame {

    private HistoriaUsuario hu;
    private int value;
    
    public HistoriaUsuarioInterfaz(/*HistoriaUsuario hu*/)  {        
        //this.hu=hu;
        initComponents();         
        barraProgreso.setValue(value);        
        //barraProgreso.setStringPainted(true);
        barraProgreso.setBackground(Color.WHITE);
        barraProgreso.setForeground(Color.YELLOW);        
        setVisible(true);
        //descripcion.setText(hu.getDescripcion());
        //importancia.setText(Integer.toString(hu.getImportancia()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        label_descripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        label_importancia = new javax.swing.JLabel();
        importancia = new javax.swing.JLabel();
        boton_aceptado = new javax.swing.JButton();
        boton_rechazado = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        label_estado = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        barraProgreso =  new javax.swing.JProgressBar(JProgressBar.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea");

        label_descripcion.setText("Descripcion:");

        label_importancia.setText("Importancia:");

        boton_aceptado.setText("Estoy de acuerdo!");
        boton_aceptado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptadoActionPerformed(evt);
            }
        });

        boton_rechazado.setText("No estoy de acuerdo...");
        boton_rechazado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_rechazadoActionPerformed(evt);
            }
        });

        boton_salir.setText("Salir");

        label_estado.setText("Estado:");

        barraProgreso.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_importancia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_descripcion)
                            .addComponent(label_estado))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importancia, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_aceptado)
                        .addGap(28, 28, 28)
                        .addComponent(boton_rechazado)
                        .addGap(31, 31, 31)
                        .addComponent(boton_salir)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_descripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_importancia))
                            .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importancia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_estado)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_aceptado)
                    .addComponent(boton_rechazado)
                    .addComponent(boton_salir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>                        

    private void boton_aceptadoActionPerformed(java.awt.event.ActionEvent evt) {  
        /*hu.aprobar();
        if(!hu.estaRechazada()){
            value+=20;        
            if(value>60)
                barraProgreso.setForeground(Color.GREEN);
            barraProgreso.setValue(value); 
        }*/
    }                                              

    private void boton_rechazadoActionPerformed(java.awt.event.ActionEvent evt) { 
        hu.rechazarHistoria("");
        barraProgreso.setForeground(Color.RED);
    }                                               


    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        dispose();       
    }
    /**
     
   
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaUsuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriaUsuarioInterfaz(new HistoriaUsuario()).setVisible(true);
            }
        });
    }  */
    

    // Variables declaration - do not modify                     
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton boton_aceptado;
    private javax.swing.JButton boton_rechazado;
    private javax.swing.JButton boton_salir;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel importancia;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_estado;
    private javax.swing.JLabel label_importancia;
    // End of variables declaration                   
}
