/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package XP.Visual;
import XP.Modelo.HistoriaUsuario;
import XP.Control.*;
import java.util.ArrayList;
import javax.swing.GroupLayout.*;
import javax.swing.*;


/**
 *
 * @author alvaro
 */
public class HomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeGUI
     */
    public HomeGUI() {
        historias = new ArrayList<ControlHU>();
        
        try
        {
            obtenerHistorias = new ObtenerHistorias();
        }
        catch( Exception e )
        {
            System.out.println(e);
        }
        
        historias = obtenerHistorias.getLista();
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backlog = new javax.swing.JPanel();
        scrollHistorias = new javax.swing.JScrollPane();
        panelHistorias = new javax.swing.JPanel();
        historia3 = new javax.swing.JPanel();
        newHistory = new javax.swing.JButton();
        botVer1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout historia3Layout = new javax.swing.GroupLayout(historia3);
        historia3.setLayout(historia3Layout);
        historia3Layout.setHorizontalGroup(
            historia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        historia3Layout.setVerticalGroup(
            historia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        
        userHistLay = new GroupLayout[historias.size()];
        
        for( int i=0; i<historias.size(); i++ )
        {
            newHistory.setText( historias.get(i).getHistoria().getNombre() );
            
            jLabel1.setText( historias.get(i).getHistoria().getNombre() );
            
            historia3.add(jLabel1);
        }
        
        //newHistory.setText("Nueva Historia");
        newHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHistoryActionPerformed(evt);
            }
        });

        botVer1.setText("Ver");
        botVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVer1ActionPerformed(evt);
            }
        });

        //jLabel1.setText("Historia 1");

        javax.swing.GroupLayout panelHistoriasLayout = new javax.swing.GroupLayout(panelHistorias);
        panelHistorias.setLayout(panelHistoriasLayout);
        panelHistoriasLayout.setHorizontalGroup(
            panelHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historia3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoriasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newHistory))
                    .addGroup(panelHistoriasLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100)
                        .addComponent(botVer1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(333, 333, 333)))
                .addContainerGap())
        );
        panelHistoriasLayout.setVerticalGroup(
            panelHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newHistory)
                .addGap(1, 1, 1)
                .addGroup(panelHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botVer1))
                .addGap(363, 363, 363)
                .addComponent(historia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        scrollHistorias.setViewportView(panelHistorias);

        javax.swing.GroupLayout backlogLayout = new javax.swing.GroupLayout(backlog);
        backlog.setLayout(backlogLayout);
        backlogLayout.setHorizontalGroup(
            backlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backlogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollHistorias, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backlogLayout.setVerticalGroup(
            backlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHistorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVer1ActionPerformed
        //actual = historias.get(0).getHistoria();
        new HistoriaUsuarioInterfaz();
    }//GEN-LAST:event_botVer1ActionPerformed

    private void newHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newHistoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backlog;
    private javax.swing.JButton botVer1;
    private javax.swing.JPanel historia3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newHistory;
    private javax.swing.JPanel panelHistorias;
    private javax.swing.JScrollPane scrollHistorias;
    private GroupLayout[] userHistLay;
    // End of variables declaration//GEN-END:variables
    private ArrayList<ControlHU> historias;
    private HistoriaUsuario actual;
    private ObtenerHistorias obtenerHistorias;
}
